global:
  scrape_interval:     10s 
  evaluation_interval: 10s 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'push-c1-e1-to-dc'
    honor_labels: false
    metrics_path: /metrics
    static_configs:
      - targets: ['172.18.0.5:30001']
  - job_name: 'push-c2-e1-to-dc'
    honor_labels: false
    metrics_path: /metrics
    static_configs:
      - targets: ['172.18.0.5:30002']          
  - job_name: 'gnmic'
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets: ['172.18.0.7:30100']


