apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgw-cust1-to-dc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgw-cust1-to-dc
  template:
    metadata:
      labels:
        app: pushgw-cust1-to-dc
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          imagePullPolicy: Never  
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /#/status
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pushsvc-cust1-to-dc
spec:
  type: NodePort
  selector:
    app: pushgw-cust1-to-dc
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 30001
