apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 1.1.1.202
      peer-asn: 65302
      my-asn: 65201
      router-id: 6.5.2.2
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [datacenter-worker2]
    - peer-address: 1.1.1.201
      peer-asn: 65301
      my-asn: 65201
      router-id: 6.5.2.3
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [datacenter-worker]
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.254.254.240/28
